### PR TITLE
shared object store for arbitrary binary data

### PR DESCRIPTION
**Pull request by araex**
In preparation for #19 i implemented a shared object storage that is synchronized between the server and all clients. 

Details:
1. Add entry using `RemoteStore.Insert(object obj)` on either server or client.
2. The object will be serialized using `StoreSerializer.Serialize`.
3. A 32 bit [xxHash](https://github.com/Cyan4973/xxHash) is computed for the serialized data.
4. The hash + serialized data is sent as a `EPacket.StoreAdd` to the end points of the current connection.
5. The end point receives the packet, reads the hash and deserializes the object using `StoreSerializer.Deserialize`.
6. The end point returns a `EPacket.StoreAck`.
7. The object is now available on all connected stores.

The store does not remove any objects, they have  to be removed explicitly. 

The inteded use case for #19 is to synchronize larger argument objects using the store. The RPC sent over persistence only contains the xxHash (32Bits). The RPC will be executed once the remote store has the object available.

### CODE REVIEW

**Comment by evorios** [comment]
Get issue "Failed to get type `Sync.Store.ObjectId`" in https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/a77d47f937c9b3f7e33f0c78cd38fab29ccb4dfd/source/Coop/Mod/CoopClient.cs#L22
Stack `Main > CoopClient.m_Instance.get`
But in `development` branch is not appear.

**Comment by araex** [comment]
> Get issue "Failed to get type `Sync.Store.ObjectId`" in
> 
> https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/a77d47f937c9b3f7e33f0c78cd38fab29ccb4dfd/source/Coop/Mod/CoopClient.cs#L22
> 
> 
> Stack `Main > CoopClient.m_Instance.get`
> But in `development` branch is not appear.

I'm unable to reproduce this. Judging from the stack this is during startup of the game?

**Comment by evorios** [comment]
> I'm unable to reproduce this. Judging from the stack this is during startup of the game?

Yes. All relative test was successful.

**Comment by evorios** [comment]
The old version of the `Sync.dll` got into the bin folder of the game. My bad =(

**Review by evorios — APPROVED** [review]

**Review by garrettluskey — APPROVED** [review]
Looks good

**Pull request merged**
