### PR TITLE
update railgun submodule

### PR DESCRIPTION
**Pull request by evorios**

### CODE REVIEW

**Comment by garrettluskey** [comment]
Can you change that in the current merge request? If you push to your branch it will update the merge request automatically.

**Comment by garrettluskey** [comment]
Unless I do not understand correctly

**Comment by evorios** [comment]
Huh? What you want? I need more info.

**Comment by garrettluskey** [comment]
@araex can you look into this one? My sub module experience isn't that great

**Review by araex — APPROVED** [review]

**Pull request merged**
